### ISSUE TITLE
App Information Architecture

### ISSUE THREAD

**Issue by Tim-Lee0001** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#21]
조금 시간이 걸렸지만 앱의 정보구조도 업로드 드립니다.
개발에 참고하시면 되겠습니다.
확인해보시고 이상한 점 있으면 말씀해주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/112791236/198862202-bc0e3f1c-a7ee-4050-a5a7-17d4efb0cbaf.png)
![image](https://user-images.githubusercontent.com/112791236/198862204-4d817196-a7e4-4050-959f-297994ffae1f.png)

**Comment by hmc0105** [comment]
정보구조도 덕에 헷갈리는 일은 없을 것 같습니다 수고하셨습니다.
