### ISSUE TITLE
PX Sample Products for AI Camera Algorithm

### ISSUE THREAD

**Issue by Tim-Lee0001** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#23]
PX에서 AI카메라 학습에 사용될 물품 목록을 정해야 합니다.
일단 카테고리별 대표 물품목록을 조사하였으니 해당목록에서 AI학습에 사용할 물품들을 채택하면 좋겠습니다.
![image](https://user-images.githubusercontent.com/112791236/198862258-ae56b4b5-7b8c-4e36-b900-7a70920076c4.png)

**Comment by leedbswo107** [comment]
개발 완료되어 이슈 닫습니다.
