### ISSUE TITLE
MLkit Barcode Recognition

### ISSUE THREAD

**Issue by EunChan719** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#26]
## MLKIT issue
MLkit를 제작할 때 flutter에서 보여주는 방식은 갤러리에서 (영수증이나 바코드 등의 )이미지를 하나 받아오고 그 이미지의 정보를 읽는 방식이었습니다. 하지만 우리가 원하고자 하는 방식은 Real Camera 형식인데 실시간으로 카메라가 영수증에 있는 가격 정보나 바코드에 있는 정보를 받아오는 방식을 구현하고 싶습니다.

**Comment by hmc0105** [comment]
그거 StreamVersion으로 바꿔서 Google ML Kit에 하면 됩니다. 별로 문제 안될 겁니다. 외출 나가서 해보죠
