### ISSUE TITLE
Implementing signup in Flutter

### ISSUE THREAD

**Issue by Tim-Lee0001** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#28]
현재 구현되고 잇는 회원가입화면에서

비밀번호 재설정
회원가입
공통적으로 google에서 제공하는 기능을 그대로 사용해도 좋을 것 같습니다.

따라서 원래 군번을 아이디로 사용하기로 했었지만,
이메일을 아이디로 변경하는 것이 좋을 것 같습니다.

**Comment by hmc0105** [comment]
아래 Sign Up Page에 말한 얘기입니다.
