### ISSUE TITLE
Recognizing barcodes in Flutter

### ISSUE THREAD

**Issue by Tim-Lee0001** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#29]
Flutter 에서 바코드를 인식하는 기능을 추가해야합니다.

[https://hitomis.tistory.com/149의](https://hitomis.tistory.com/149%EC%9D%98) 예시와 같이 Barcode를 인식하도록 해야하는데,
MLkit에서 제공하는
https://developers.google.com/ml-kit/vision/barcode-scanning
스캔 기능을 사용해도 좋을 것 같습니다.

**Comment by hmc0105** [comment]
옙 이거 따라서 구현하겠습니다.
