### ISSUE TITLE
Autocomplete Input Function

### ISSUE THREAD

**Issue by EunChan719** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#32]
TextField를 제작할때 Autocomplete 기능을 넣고 싶었습니다. 이때 Autocomplete class를 사용하면 되었는데 이때 Autocomplete class를 사용하면 textformfield를 어떻게 사용할 수 있는지가 어려운 난관이었습니다. 그리고 autocomplete를 사용하면 자동완성위젯이 오른쪽 화면 밖으로 나가는 error가 있습니다.

**Comment by hmc0105** [comment]
@leedbswo107 해결좀

**Comment by leedbswo107** [comment]
개발 완료되어 이슈 닫습니다.
