### ISSUE TITLE
Password Reset 

### ISSUE THREAD

**Issue by EunChan719** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#33]
초기에는 비밀번호 변경하기 페이지에서 비밀번호 변경할때는 이름과 이메일 부대코드,군번이 입력 되어야 했는데  군번이 Firebase에서 이메일 패스워드 조합만 지원하는 바람에 이메일 정보만 받아와서 패스워드를 변경할 것입니다.
![image](https://user-images.githubusercontent.com/72517939/198862451-a4791b1e-df51-48ce-b02e-6d794a86017b.png)

**Comment by leedbswo107** [comment]
개발 완료되어 이슈 닷습니다.
