### ISSUE TITLE
Barcode Scan Camera

### ISSUE THREAD

**Issue by EunChan719** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#34]
초기에는 바코드를 인식할 때 탭바에서 "바코드 인식"을 누르면 바로 카메라가 나오는 형식 이었는데 "카메라 인식하기" 버튼을 따로 만들어 바로 카메라가 바로 켜지는 것이 아니라 버튼을 누르면 카메라로 이동되는 형식으로 제작하고 있습니다. 
![image](https://user-images.githubusercontent.com/72517939/198862520-d04adac7-c5d6-4620-b7d3-11edb2d3268a.png)

**Comment by hmc0105** [comment]
그렇습니다
