### ISSUE TITLE
Logo Svg Print Error

### ISSUE THREAD

**Issue by leedbswo107** [osamhack2022-v2/APP_FreshPlus_TakeCareMyRefrigerator#35]
**SVG Image Error**

Splash 에서 Logo 부분이 SVG 파일임에도 뒤에 background 상자가 만들어지는 오류를 발견했습니다. 해당 오류는 logo를 다양한곳에서 
import 해서 쓸수 있게 작업하던중 발생한것으로 보여 해결하도록 하겠습니다.

**Comment by leedbswo107** [comment]
Splash 에서 logo svg 파일이 container에 담긴것으로 출력되는 오류를 해결하기 위해 기존 logo 파일에서 MaterialApp 에서 child로 Column 을 return 했는데 MaterialApp을 없애고 Column 을 바로 return 하는 방식으로 수정했습니다.

**Comment by hmc0105** [comment]
final에 반영했습니다. 감사합니다.
